#!/usr/bin/env python3
"""Reproducible Tier-1 laboratory for the Double-Pendulum Operational Atlas.

The laboratory integrates a cell-centred initial-angle grid, constructs the
finite-horizon operational fields in :mod:`oig_double_pendulum_atlas`, and
records energy and all-cell tolerance-refinement diagnostics. Its report is a
numerical discovery artifact.  It does not claim an outward enclosure of the
exact nonlinear flow.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass
import json
import math
from pathlib import Path
import platform
import re
from typing import Sequence

import numpy as np
import scipy

from double_pendulum_dynamics import (
    DoublePendulumParameters,
    IntegrationConfig,
    refinement_diagnostic,
    simulate_double_pendulum,
    total_energy,
)
from oig_double_pendulum_atlas import (
    OperationalAtlas,
    build_operational_atlas,
    cell_centred_torus_grid,
    toroidal_connected_components,
)


SCHEMA_VERSION = "oig-double-pendulum-tier1-atlas-v2"
DYNAMICS_VARIANT = "conservative point masses on massless rigid rods"
INITIAL_SLICE = "cell-centred absolute-angle torus with omega1=omega2=0"
ACCEPTANCE_STATUS = "provisional_tier1"
REMAINING_GATES = [
    "grid-side and half-cell-shift persistence",
    "horizon persistence",
    "observation-cadence persistence",
]
PROOF_BOUNDARY = (
    "This is a reproducible finite-time numerical discovery report. Energy and "
    "all-cell refinement gates are empirical diagnostics, not an interval enclosure of the "
    "exact flow. Sampled turn excursions can miss between-sample events; grid-edge "
    "stretch is not a Jacobian singular value; connected threshold regions are not "
    "mutual-indistinguishability classes. Grid, horizon, and cadence persistence "
    "remain open, so this artifact is provisional Tier 1. The internal verifier "
    "does not prove that serialized raw arrays were generated by the declared ODE."
)


def _verification_payload() -> dict[str, object]:
    return {
        "passed": True,
        "method": "same-module internal consistency reconstruction of Tier-1 contract, gates, and raw-array summaries",
        "claim_tier": 1,
        "report_provenance_authenticated": False,
        "declared_ode_to_raw_array_link_verified": False,
        "physical_flow_enclosure_verified": False,
    }


@dataclass(frozen=True)
class AtlasRunConfig:
    """Finite numerical experiment declaration."""

    side: int = 13
    duration: float = 4.0
    observation_count: int = 81
    feature_sample_count: int = 9
    log_stretch_threshold: float = 0.5
    refinement_scaled_state_tolerance: float = 2.0e-7

    def __post_init__(self) -> None:
        if type(self.side) is not int or self.side < 3:
            raise ValueError("side must be an integer at least three")
        duration = float(self.duration)
        threshold = float(self.log_stretch_threshold)
        refinement_tolerance = float(self.refinement_scaled_state_tolerance)
        if not math.isfinite(duration) or duration <= 0:
            raise ValueError("duration must be finite and positive")
        if type(self.observation_count) is not int or self.observation_count < 3:
            raise ValueError("observation_count must be an integer at least three")
        if (
            type(self.feature_sample_count) is not int
            or not 2 <= self.feature_sample_count <= self.observation_count
        ):
            raise ValueError("feature_sample_count lies outside the observation grid")
        if not math.isfinite(threshold):
            raise ValueError("log_stretch_threshold must be finite")
        if (
            not math.isfinite(refinement_tolerance)
            or refinement_tolerance <= 0
        ):
            raise ValueError("refinement tolerance must be finite and positive")
        object.__setattr__(self, "duration", duration)
        object.__setattr__(self, "log_stretch_threshold", threshold)
        object.__setattr__(
            self, "refinement_scaled_state_tolerance", refinement_tolerance
        )


def _config_record(config: IntegrationConfig) -> dict[str, object]:
    return {
        "rtol": config.rtol,
        "atol": config.atol,
        "max_step": config.max_step,
        "energy_drift_tolerance": config.energy_drift_tolerance,
    }


def _parameter_record(parameters: DoublePendulumParameters) -> dict[str, float]:
    return {
        "m1": parameters.m1,
        "m2": parameters.m2,
        "l1": parameters.l1,
        "l2": parameters.l2,
        "g": parameters.g,
    }


def _audit_cells(side: int) -> tuple[tuple[int, int], ...]:
    """All cells, in deterministic row-major order."""
    return tuple((row, column) for row in range(side) for column in range(side))


def simulate_initial_angle_grid(
    run: AtlasRunConfig,
    parameters: DoublePendulumParameters,
    integration: IntegrationConfig,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return times, states, scaled energy drift, and initial energy fields."""
    _, _, initial = cell_centred_torus_grid(run.side)
    times = np.linspace(0.0, run.duration, run.observation_count)
    states = np.empty((run.observation_count, run.side, run.side, 4), dtype=float)
    energy_drift = np.empty((run.side, run.side), dtype=float)
    initial_energy = total_energy(initial, parameters)
    for row in range(run.side):
        for column in range(run.side):
            trajectory = simulate_double_pendulum(
                initial[row, column], times, parameters, integration
            )
            states[:, row, column, :] = trajectory.states
            energy_drift[row, column] = trajectory.max_scaled_energy_drift
    return times, states, energy_drift, np.asarray(initial_energy, dtype=float)


def run_atlas_lab(
    run: AtlasRunConfig = AtlasRunConfig(),
    parameters: DoublePendulumParameters = DoublePendulumParameters(),
    integration: IntegrationConfig = IntegrationConfig(
        rtol=1.0e-10,
        atol=1.0e-12,
        max_step=0.015,
        energy_drift_tolerance=2.0e-9,
    ),
) -> tuple[dict[str, object], OperationalAtlas]:
    """Run the canonical numerical atlas and return its report and raw object."""
    if integration.energy_drift_tolerance is None:
        raise ValueError("a Tier-1 atlas requires an enforced energy-drift gate")
    times, states, energy_drift, initial_energy = simulate_initial_angle_grid(
        run, parameters, integration
    )
    sample_indices = np.linspace(
        0, run.observation_count - 1, run.feature_sample_count, dtype=int
    )
    candidate_atlas = build_operational_atlas(
        states,
        sample_indices=tuple(int(value) for value in sample_indices),
        log_stretch_threshold=run.log_stretch_threshold,
        angular_velocity_scale=parameters.characteristic_angular_speed,
    )

    refinement_rows: list[dict[str, object]] = []
    resolved = np.zeros((run.side, run.side), dtype=bool)
    for row, column in _audit_cells(run.side):
        diagnostic = refinement_diagnostic(
            states[0, row, column],
            times,
            parameters,
            coarse_config=integration,
            scaled_state_tolerance=run.refinement_scaled_state_tolerance,
        )
        refinement_rows.append(
            {
                "row": row,
                "column": column,
                "initial_angles": [
                    float(states[0, row, column, 0]),
                    float(states[0, row, column, 1]),
                ],
                "max_component_discrepancy": [
                    float(value) for value in diagnostic.max_component_discrepancy
                ],
                "max_unwrapped_angle_discrepancy": [
                    float(value)
                    for value in diagnostic.max_unwrapped_angle_discrepancy
                ],
                "sampled_full_turn_events_consistent": (
                    diagnostic.sampled_full_turn_events_consistent
                ),
                "coarse_first_sampled_full_turn_indices": [
                    int(value)
                    for value in diagnostic.coarse_first_sampled_full_turn_indices
                ],
                "fine_first_sampled_full_turn_indices": [
                    int(value)
                    for value in diagnostic.fine_first_sampled_full_turn_indices
                ],
                "max_scaled_state_discrepancy": diagnostic.max_scaled_state_discrepancy,
                "passed": diagnostic.passed,
            }
        )
        resolved[row, column] = diagnostic.passed

    resolved_mask = (
        candidate_atlas.low_stretch_no_sampled_full_turn_mask & resolved
    )
    resolved_labels, resolved_sizes = toroidal_connected_components(resolved_mask)
    atlas = OperationalAtlas(
        feature=candidate_atlas.feature,
        log_stretch=candidate_atlas.log_stretch,
        first_sampled_turn_excursion_arm_1=(
            candidate_atlas.first_sampled_turn_excursion_arm_1
        ),
        first_sampled_turn_excursion_arm_2=(
            candidate_atlas.first_sampled_turn_excursion_arm_2
        ),
        low_stretch_no_sampled_full_turn_mask=resolved_mask,
        component_labels=resolved_labels,
        component_sizes=resolved_sizes,
        log_stretch_threshold=run.log_stretch_threshold,
    )
    reflected_stretch_error = float(
        np.max(np.abs(atlas.log_stretch - atlas.log_stretch[::-1, ::-1]))
    )
    reflected_energy_error = float(
        np.max(np.abs(initial_energy - initial_energy[::-1, ::-1]))
    )
    reflected_mask_equal = bool(
        np.array_equal(resolved_mask, resolved_mask[::-1, ::-1])
    )
    reflection_tolerance = 1.0e-6
    reflection_passed = bool(
        reflected_stretch_error <= reflection_tolerance
        and reflected_energy_error <= reflection_tolerance
        and reflected_mask_equal
    )

    report: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "claim_tier": 1,
        "dynamics_variant": DYNAMICS_VARIANT,
        "state_convention": ["theta1", "theta2", "omega1", "omega2"],
        "initial_slice": INITIAL_SLICE,
        "parameters": _parameter_record(parameters),
        "integration": _config_record(integration),
        "refinement_integration": _config_record(integration.refined()),
        "experiment_contract": {
            "solver": "scipy.integrate.solve_ivp/DOP853 with dense output",
            "energy_audit": "accepted endpoints, accepted-step midpoints, and observation times",
            "grid_topology": "cell-centred half-open product torus",
            "grid_axis_0": "theta1 increasing from -pi to pi",
            "grid_axis_1": "theta2 increasing from -pi to pi",
            "initial_angular_velocities": [0.0, 0.0],
            "observation_map": "phase_observation-v1",
            "observation_coordinates": [
                "sin(theta1)",
                "cos(theta1)",
                "sin(theta2)",
                "cos(theta2)",
                "omega1/angular_velocity_scale",
                "omega2/angular_velocity_scale",
            ],
            "angular_velocity_scale": parameters.characteristic_angular_speed,
            "feature_sample_weights": "equal RMS weights",
            "local_stretch_directions": "four periodic axis-neighbour grid edges",
        },
        "run": asdict(run),
        "observation_times": [float(value) for value in times],
        "feature_sample_indices": [int(value) for value in sample_indices],
        "atlas_summary": atlas.summary(),
        "maximum_sampled_scaled_energy_drift": float(np.max(energy_drift)),
        "energy_drift_quantiles": {
            "q50": float(np.quantile(energy_drift, 0.50)),
            "q90": float(np.quantile(energy_drift, 0.90)),
            "q100": float(np.max(energy_drift)),
        },
        "initial_energy_range": [
            float(np.min(initial_energy)),
            float(np.max(initial_energy)),
        ],
        "refinement_audits": refinement_rows,
        "all_refinement_audits_passed": all(
            bool(row["passed"]) for row in refinement_rows
        ),
        "resolved_cell_count": int(np.count_nonzero(resolved)),
        "unresolved_cell_count": int(resolved.size - np.count_nonzero(resolved)),
        "reflection_audit": {
            "joint_angle_reflection": "(theta1,theta2)->(-theta1,-theta2)",
            "tolerance": reflection_tolerance,
            "log_stretch_max_absolute_discrepancy": reflected_stretch_error,
            "initial_energy_max_absolute_discrepancy": reflected_energy_error,
            "resolved_mask_exactly_reflection_symmetric": reflected_mask_equal,
            "passed": reflection_passed,
        },
        "acceptance_status": ACCEPTANCE_STATUS,
        "remaining_numerical_acceptance_gates": list(REMAINING_GATES),
        "raw_fields": {
            "grid_edge_log_stretch": atlas.log_stretch.tolist(),
            "sampled_turn_excursion_arm_1": (
                atlas.first_sampled_turn_excursion_arm_1.tolist()
            ),
            "sampled_turn_excursion_arm_2": (
                atlas.first_sampled_turn_excursion_arm_2.tolist()
            ),
            "candidate_low_stretch_no_sampled_full_turn_mask": (
                candidate_atlas.low_stretch_no_sampled_full_turn_mask.astype(int).tolist()
            ),
            "convergence_resolved_mask": resolved.astype(int).tolist(),
            "resolved_low_stretch_no_sampled_full_turn_mask": (
                atlas.low_stretch_no_sampled_full_turn_mask.astype(int).tolist()
            ),
            "connected_region_labels": atlas.component_labels.tolist(),
            "initial_energy": initial_energy.tolist(),
            "sampled_scaled_energy_drift": energy_drift.tolist(),
        },
        "environment": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "scipy": scipy.__version__,
        },
        "proof_boundary": PROOF_BOUNDARY,
    }
    verification = verify_atlas_lab_report(report)
    if not verification["passed"]:
        raise AssertionError(f"atlas report self-verification failed: {verification}")
    report["internal_consistency_verification"] = verification
    return report, atlas


def _same_json_value(left: object, right: object) -> bool:
    """Strict recursive equality that does not identify booleans with integers."""
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        return left.keys() == right.keys() and all(
            _same_json_value(left[key], right[key]) for key in left
        )
    if isinstance(left, list):
        return len(left) == len(right) and all(
            _same_json_value(a, b) for a, b in zip(left, right)
        )
    return left == right


def _finite_number(value: object, name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{name} must be a JSON number")
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{name} must be finite")
    return result


def _numeric_grid(value: object, side: int, name: str) -> np.ndarray:
    if not isinstance(value, list) or len(value) != side:
        raise ValueError(f"{name} must have {side} rows")
    rows: list[list[float]] = []
    for row_index, row in enumerate(value):
        if not isinstance(row, list) or len(row) != side:
            raise ValueError(f"{name}[{row_index}] has the wrong width")
        rows.append(
            [
                _finite_number(entry, f"{name}[{row_index}][{column}]")
                for column, entry in enumerate(row)
            ]
        )
    return np.asarray(rows, dtype=float)


def _integer_grid(value: object, side: int, name: str) -> np.ndarray:
    if not isinstance(value, list) or len(value) != side:
        raise ValueError(f"{name} must have {side} rows")
    rows: list[list[int]] = []
    for row_index, row in enumerate(value):
        if not isinstance(row, list) or len(row) != side:
            raise ValueError(f"{name}[{row_index}] has the wrong width")
        parsed: list[int] = []
        for column, entry in enumerate(row):
            if type(entry) is not int:
                raise ValueError(
                    f"{name}[{row_index}][{column}] must be a JSON integer"
                )
            parsed.append(entry)
        rows.append(parsed)
    return np.asarray(rows, dtype=int)


def verify_atlas_lab_report(report: dict[str, object]) -> dict[str, object]:
    """Check contract, gates, and summaries against serialized Tier-1 fields.

    This remains an internal-consistency verifier. It does not rerun the ODE,
    authenticate file provenance, or upgrade the numerical claim tier.
    """
    try:
        if not isinstance(report, dict):
            raise ValueError("atlas report must be a JSON object")
        expected_top_level = {
            "schema_version",
            "claim_tier",
            "dynamics_variant",
            "state_convention",
            "initial_slice",
            "parameters",
            "integration",
            "refinement_integration",
            "experiment_contract",
            "run",
            "observation_times",
            "feature_sample_indices",
            "atlas_summary",
            "maximum_sampled_scaled_energy_drift",
            "energy_drift_quantiles",
            "initial_energy_range",
            "refinement_audits",
            "all_refinement_audits_passed",
            "resolved_cell_count",
            "unresolved_cell_count",
            "reflection_audit",
            "acceptance_status",
            "remaining_numerical_acceptance_gates",
            "raw_fields",
            "environment",
            "proof_boundary",
        }
        actual_top_level = set(report)
        if actual_top_level not in (
            expected_top_level,
            expected_top_level | {"internal_consistency_verification"},
        ):
            raise ValueError("atlas report top-level schema is inconsistent")
        if report.get("schema_version") != SCHEMA_VERSION:
            raise ValueError("unknown atlas report schema")
        if type(report.get("claim_tier")) is not int or report["claim_tier"] != 1:
            raise ValueError("the numerical atlas must declare claim tier one")
        if report.get("dynamics_variant") != DYNAMICS_VARIANT:
            raise ValueError("dynamics variant is inconsistent")
        if report.get("initial_slice") != INITIAL_SLICE:
            raise ValueError("initial slice is inconsistent")
        if report.get("state_convention") != ["theta1", "theta2", "omega1", "omega2"]:
            raise ValueError("state convention is inconsistent")
        run = report.get("run")
        raw = report.get("raw_fields")
        parameters_record = report.get("parameters")
        integration_record = report.get("integration")
        refinement_integration_record = report.get("refinement_integration")
        contract = report.get("experiment_contract")
        if not all(
            isinstance(value, dict)
            for value in (
                run,
                raw,
                parameters_record,
                integration_record,
                refinement_integration_record,
                contract,
            )
        ):
            raise ValueError("contract, parameters, integrations, run, and raw fields must be objects")
        assert isinstance(run, dict)
        assert isinstance(raw, dict)
        assert isinstance(parameters_record, dict)
        assert isinstance(integration_record, dict)
        assert isinstance(refinement_integration_record, dict)
        assert isinstance(contract, dict)
        expected_run_keys = {
            "side",
            "duration",
            "observation_count",
            "feature_sample_count",
            "log_stretch_threshold",
            "refinement_scaled_state_tolerance",
        }
        if set(run) != expected_run_keys:
            raise ValueError("run declaration keys are inconsistent")
        side = run.get("side")
        if type(side) is not int or side < 3:
            raise ValueError("invalid serialized side")
        declaration = AtlasRunConfig(
            side=side,
            duration=_finite_number(run["duration"], "run.duration"),
            observation_count=run["observation_count"],  # type: ignore[arg-type]
            feature_sample_count=run["feature_sample_count"],  # type: ignore[arg-type]
            log_stretch_threshold=_finite_number(
                run["log_stretch_threshold"], "run.log_stretch_threshold"
            ),
            refinement_scaled_state_tolerance=_finite_number(
                run["refinement_scaled_state_tolerance"],
                "run.refinement_scaled_state_tolerance",
            ),
        )
        if type(run["observation_count"]) is not int or type(run["feature_sample_count"]) is not int:
            raise ValueError("observation and feature counts must be JSON integers")
        if set(parameters_record) != {"m1", "m2", "l1", "l2", "g"}:
            raise ValueError("physical parameter keys are inconsistent")
        parameters = DoublePendulumParameters(
            **{
                key: _finite_number(value, f"parameters.{key}")
                for key, value in parameters_record.items()
            }
        )
        if set(integration_record) != {
            "rtol",
            "atol",
            "max_step",
            "energy_drift_tolerance",
        }:
            raise ValueError("integration declaration keys are inconsistent")
        energy_gate = integration_record["energy_drift_tolerance"]
        if energy_gate is None:
            raise ValueError("Tier-1 report disabled the energy gate")
        integration = IntegrationConfig(
            rtol=_finite_number(integration_record["rtol"], "integration.rtol"),
            atol=_finite_number(integration_record["atol"], "integration.atol"),
            max_step=_finite_number(
                integration_record["max_step"], "integration.max_step"
            ),
            energy_drift_tolerance=_finite_number(
                energy_gate, "integration.energy_drift_tolerance"
            ),
        )
        expected_refinement_integration = _config_record(integration.refined())
        if not _same_json_value(
            refinement_integration_record, expected_refinement_integration
        ):
            raise ValueError("refinement integration does not match the declared rule")
        expected_contract = {
            "solver": "scipy.integrate.solve_ivp/DOP853 with dense output",
            "energy_audit": "accepted endpoints, accepted-step midpoints, and observation times",
            "grid_topology": "cell-centred half-open product torus",
            "grid_axis_0": "theta1 increasing from -pi to pi",
            "grid_axis_1": "theta2 increasing from -pi to pi",
            "initial_angular_velocities": [0.0, 0.0],
            "observation_map": "phase_observation-v1",
            "observation_coordinates": [
                "sin(theta1)",
                "cos(theta1)",
                "sin(theta2)",
                "cos(theta2)",
                "omega1/angular_velocity_scale",
                "omega2/angular_velocity_scale",
            ],
            "angular_velocity_scale": parameters.characteristic_angular_speed,
            "feature_sample_weights": "equal RMS weights",
            "local_stretch_directions": "four periodic axis-neighbour grid edges",
        }
        if not _same_json_value(contract, expected_contract):
            raise ValueError("experiment contract is inconsistent")
        times = report.get("observation_times")
        if not isinstance(times, list) or len(times) != declaration.observation_count:
            raise ValueError("observation time grid has the wrong length")
        parsed_times = [
            _finite_number(value, f"observation_times[{index}]")
            for index, value in enumerate(times)
        ]
        expected_times = [
            float(value)
            for value in np.linspace(
                0.0, declaration.duration, declaration.observation_count
            )
        ]
        if parsed_times != expected_times:
            raise ValueError("observation time grid does not reconstruct")
        feature_indices = report.get("feature_sample_indices")
        if (
            not isinstance(feature_indices, list)
            or any(type(value) is not int for value in feature_indices)
            or feature_indices
            != [
                int(value)
                for value in np.linspace(
                    0,
                    declaration.observation_count - 1,
                    declaration.feature_sample_count,
                    dtype=int,
                )
            ]
        ):
            raise ValueError("feature sample indices do not reconstruct")

        expected_raw_keys = {
            "grid_edge_log_stretch",
            "sampled_turn_excursion_arm_1",
            "sampled_turn_excursion_arm_2",
            "candidate_low_stretch_no_sampled_full_turn_mask",
            "convergence_resolved_mask",
            "resolved_low_stretch_no_sampled_full_turn_mask",
            "connected_region_labels",
            "initial_energy",
            "sampled_scaled_energy_drift",
        }
        if set(raw) != expected_raw_keys:
            raise ValueError("raw field keys are inconsistent")
        stretch = _numeric_grid(raw["grid_edge_log_stretch"], side, "stretch")
        turn_1 = _integer_grid(raw["sampled_turn_excursion_arm_1"], side, "turn_1")
        turn_2 = _integer_grid(raw["sampled_turn_excursion_arm_2"], side, "turn_2")
        candidate_int = _integer_grid(
            raw["candidate_low_stretch_no_sampled_full_turn_mask"],
            side,
            "candidate_mask",
        )
        resolved_int = _integer_grid(
            raw["convergence_resolved_mask"], side, "resolved_mask"
        )
        mask_int = _integer_grid(
            raw["resolved_low_stretch_no_sampled_full_turn_mask"],
            side,
            "reported_mask",
        )
        labels_stored = _integer_grid(
            raw["connected_region_labels"], side, "labels"
        )
        initial_energy = _numeric_grid(raw["initial_energy"], side, "initial_energy")
        energy_drift = _numeric_grid(
            raw["sampled_scaled_energy_drift"], side, "energy_drift"
        )
        if np.any(energy_drift < 0) or np.max(energy_drift) > integration.energy_drift_tolerance:
            raise ValueError("sampled energy drift violates the declared gate")
        for name, values in (("turn_1", turn_1), ("turn_2", turn_2)):
            if np.any(
                (values != -1)
                & ((values < 1) | (values >= declaration.observation_count))
            ):
                raise ValueError(f"{name} contains an invalid sampled-event index")
        expected_energy = np.asarray(
            total_energy(cell_centred_torus_grid(side)[2], parameters), dtype=float
        )
        energy_tolerance = 64.0 * np.finfo(float).eps * max(
            1.0, float(np.max(np.abs(expected_energy)))
        )
        if not np.allclose(
            initial_energy,
            expected_energy,
            rtol=0.0,
            atol=energy_tolerance,
        ):
            raise ValueError("initial-energy field does not reconstruct from grid and parameters")
        for name, values in (
            ("candidate mask", candidate_int),
            ("resolved mask", resolved_int),
            ("reported mask", mask_int),
        ):
            if np.any((values != 0) & (values != 1)):
                raise ValueError(f"{name} must contain only zero and one")
        candidate = candidate_int.astype(bool)
        expected_candidate = (
            (stretch <= declaration.log_stretch_threshold)
            & (turn_1 < 0)
            & (turn_2 < 0)
        )
        if not np.array_equal(candidate, expected_candidate):
            raise ValueError("candidate low-stretch mask does not reconstruct")

        audits = report.get("refinement_audits")
        if not isinstance(audits, list) or len(audits) != side * side:
            raise ValueError("all-cell refinement audit list is incomplete")
        expected_audit_keys = {
            "row",
            "column",
            "initial_angles",
            "max_component_discrepancy",
            "max_unwrapped_angle_discrepancy",
            "sampled_full_turn_events_consistent",
            "coarse_first_sampled_full_turn_indices",
            "fine_first_sampled_full_turn_indices",
            "max_scaled_state_discrepancy",
            "passed",
        }
        resolved_from_rows = np.zeros((side, side), dtype=bool)
        _, _, expected_initial = cell_centred_torus_grid(side)
        seen: set[tuple[int, int]] = set()
        for index, row_record in enumerate(audits):
            if not isinstance(row_record, dict) or set(row_record) != expected_audit_keys:
                raise ValueError(f"refinement_audits[{index}] has an invalid schema")
            row_index = row_record["row"]
            column_index = row_record["column"]
            if (
                type(row_index) is not int
                or type(column_index) is not int
                or not 0 <= row_index < side
                or not 0 <= column_index < side
                or (row_index, column_index) in seen
            ):
                raise ValueError("refinement audit coordinates are invalid or duplicated")
            seen.add((row_index, column_index))
            expected_angles = [
                float(expected_initial[row_index, column_index, 0]),
                float(expected_initial[row_index, column_index, 1]),
            ]
            initial_angles = row_record["initial_angles"]
            if not isinstance(initial_angles, list) or len(initial_angles) != 2:
                raise ValueError("refinement initial angles must be a two-vector")
            parsed_initial_angles = [
                _finite_number(value, "refinement initial angle")
                for value in initial_angles
            ]
            if initial_angles != parsed_initial_angles or parsed_initial_angles != expected_angles:
                raise ValueError("refinement initial angles are inconsistent")
            component = row_record["max_component_discrepancy"]
            unwrapped = row_record["max_unwrapped_angle_discrepancy"]
            coarse_turns = row_record["coarse_first_sampled_full_turn_indices"]
            fine_turns = row_record["fine_first_sampled_full_turn_indices"]
            if not isinstance(component, list) or len(component) != 4:
                raise ValueError("component discrepancy must be a four-vector")
            if not isinstance(unwrapped, list) or len(unwrapped) != 2:
                raise ValueError("unwrapped discrepancy must be a two-vector")
            component_values = [
                _finite_number(value, "component discrepancy") for value in component
            ]
            unwrapped_values = [
                _finite_number(value, "unwrapped discrepancy") for value in unwrapped
            ]
            if any(value < 0 for value in component_values + unwrapped_values):
                raise ValueError("refinement discrepancies must be nonnegative")
            if (
                not isinstance(coarse_turns, list)
                or not isinstance(fine_turns, list)
                or len(coarse_turns) != 2
                or len(fine_turns) != 2
                or any(type(value) is not int for value in coarse_turns + fine_turns)
            ):
                raise ValueError("sampled turn indices must be integer two-vectors")
            for turn_index in coarse_turns + fine_turns:
                if turn_index != -1 and not 1 <= turn_index < declaration.observation_count:
                    raise ValueError("a refinement sampled-turn index is outside its domain")
            if coarse_turns != [
                int(turn_1[row_index, column_index]),
                int(turn_2[row_index, column_index]),
            ]:
                raise ValueError("coarse refinement turns do not match the raw trajectory field")
            consistent = coarse_turns == fine_turns
            if row_record["sampled_full_turn_events_consistent"] is not consistent:
                raise ValueError("sampled turn consistency flag is false")
            scaled = _finite_number(
                row_record["max_scaled_state_discrepancy"],
                "max_scaled_state_discrepancy",
            )
            if scaled < 0:
                raise ValueError("scaled discrepancy must be nonnegative")
            expected_scaled = max(
                component_values[0],
                component_values[1],
                component_values[2] / parameters.characteristic_angular_speed,
                component_values[3] / parameters.characteristic_angular_speed,
            )
            if scaled != expected_scaled:
                raise ValueError("scaled discrepancy does not reconstruct from components")
            if any(
                component_values[index] > unwrapped_values[index] + 8.0 * np.finfo(float).eps
                for index in range(2)
            ):
                raise ValueError("wrapped angle discrepancy exceeds its unwrapped counterpart")
            passed = bool(
                scaled <= declaration.refinement_scaled_state_tolerance
                and max(unwrapped_values) <= declaration.refinement_scaled_state_tolerance
                and consistent
            )
            if type(row_record["passed"]) is not bool or row_record["passed"] is not passed:
                raise ValueError("refinement pass flag does not reconstruct")
            resolved_from_rows[row_index, column_index] = passed
        if seen != set(_audit_cells(side)):
            raise ValueError("refinement audits do not cover every grid cell")
        if not np.array_equal(resolved_int.astype(bool), resolved_from_rows):
            raise ValueError("convergence-resolved mask does not reconstruct")
        reported_mask = mask_int.astype(bool)
        if not np.array_equal(reported_mask, candidate & resolved_from_rows):
            raise ValueError("reported mask does not exclude unresolved cells")
        labels, sizes = toroidal_connected_components(reported_mask)
        if not np.array_equal(labels_stored, labels):
            raise ValueError("connected-region labels do not reconstruct")

        reconstructed = OperationalAtlas(
            feature=np.empty((side, side, 0), dtype=float),
            log_stretch=stretch,
            first_sampled_turn_excursion_arm_1=turn_1,
            first_sampled_turn_excursion_arm_2=turn_2,
            low_stretch_no_sampled_full_turn_mask=reported_mask,
            component_labels=labels,
            component_sizes=sizes,
            log_stretch_threshold=declaration.log_stretch_threshold,
        ).summary()
        if not _same_json_value(report["atlas_summary"], reconstructed):
            raise ValueError("atlas summary does not reconstruct from raw fields")

        energy_quantiles = {
            "q50": float(np.quantile(energy_drift, 0.50)),
            "q90": float(np.quantile(energy_drift, 0.90)),
            "q100": float(np.max(energy_drift)),
        }
        if report["maximum_sampled_scaled_energy_drift"] != energy_quantiles["q100"]:
            raise ValueError("maximum energy drift is inconsistent")
        if not _same_json_value(report["energy_drift_quantiles"], energy_quantiles):
            raise ValueError("energy drift quantiles are inconsistent")
        if report["initial_energy_range"] != [
            float(np.min(initial_energy)),
            float(np.max(initial_energy)),
        ]:
            raise ValueError("initial energy range is inconsistent")

        all_passed = bool(np.all(resolved_from_rows))
        if report["all_refinement_audits_passed"] is not all_passed:
            raise ValueError("aggregate refinement flag is inconsistent")
        resolved_count = report.get("resolved_cell_count")
        unresolved_count = report.get("unresolved_cell_count")
        if type(resolved_count) is not int or resolved_count != int(
            np.count_nonzero(resolved_from_rows)
        ):
            raise ValueError("resolved cell count is inconsistent")
        if type(unresolved_count) is not int or unresolved_count != int(
            resolved_from_rows.size - np.count_nonzero(resolved_from_rows)
        ):
            raise ValueError("unresolved cell count is inconsistent")
        reflection = report.get("reflection_audit")
        if not isinstance(reflection, dict):
            raise ValueError("reflection audit is missing")
        reflection_tolerance = _finite_number(
            reflection.get("tolerance"), "reflection tolerance"
        )
        if reflection_tolerance != 1.0e-6:
            raise ValueError("reflection tolerance is inconsistent")
        expected_reflection = {
            "joint_angle_reflection": "(theta1,theta2)->(-theta1,-theta2)",
            "tolerance": reflection_tolerance,
            "log_stretch_max_absolute_discrepancy": float(
                np.max(np.abs(stretch - stretch[::-1, ::-1]))
            ),
            "initial_energy_max_absolute_discrepancy": float(
                np.max(np.abs(initial_energy - initial_energy[::-1, ::-1]))
            ),
            "resolved_mask_exactly_reflection_symmetric": bool(
                np.array_equal(reported_mask, reported_mask[::-1, ::-1])
            ),
        }
        expected_reflection["passed"] = bool(
            expected_reflection["log_stretch_max_absolute_discrepancy"]
            <= reflection_tolerance
            and expected_reflection["initial_energy_max_absolute_discrepancy"]
            <= reflection_tolerance
            and expected_reflection["resolved_mask_exactly_reflection_symmetric"]
        )
        if not _same_json_value(reflection, expected_reflection):
            raise ValueError("reflection audit does not reconstruct")
        if report.get("acceptance_status") != ACCEPTANCE_STATUS:
            raise ValueError("numerical acceptance status is inconsistent")
        if report.get("remaining_numerical_acceptance_gates") != REMAINING_GATES:
            raise ValueError("remaining numerical gates are inconsistent")
        if report.get("proof_boundary") != PROOF_BOUNDARY:
            raise ValueError("claim-tier proof boundary is inconsistent")
        environment = report.get("environment")
        if not isinstance(environment, dict) or set(environment) != {
            "python",
            "numpy",
            "scipy",
        }:
            raise ValueError("environment declaration is malformed")
        version_pattern = re.compile(r"[0-9]+(?:\.[0-9]+){1,3}(?:[A-Za-z0-9.+-]*)?")
        if any(
            not isinstance(value, str) or version_pattern.fullmatch(value) is None
            for value in environment.values()
        ):
            raise ValueError("environment versions are malformed")
        verification = _verification_payload()
        embedded = report.get("internal_consistency_verification")
        if embedded is not None and not _same_json_value(embedded, verification):
            raise ValueError("embedded internal verification does not reconstruct")
        return verification
    except Exception as error:
        return {"passed": False, "error": str(error)}


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--side", type=int, default=13)
    parser.add_argument("--duration", type=float, default=4.0)
    parser.add_argument("--observations", type=int, default=81)
    parser.add_argument("--feature-samples", type=int, default=9)
    parser.add_argument("--log-stretch-threshold", type=float, default=0.5)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--verify", type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = _parser().parse_args(argv)
    if arguments.verify is not None:
        if arguments.output is not None:
            raise ValueError("--output and --verify cannot be combined")
        report = json.loads(arguments.verify.read_text(encoding="utf-8"))
        verification = verify_atlas_lab_report(report)
        print(json.dumps(verification, indent=2, sort_keys=True))
        return 0 if verification["passed"] else 1
    declaration = AtlasRunConfig(
        side=arguments.side,
        duration=arguments.duration,
        observation_count=arguments.observations,
        feature_sample_count=arguments.feature_samples,
        log_stretch_threshold=arguments.log_stretch_threshold,
    )
    report, _ = run_atlas_lab(declaration)
    payload = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if arguments.output is None:
        print(payload, end="")
    else:
        arguments.output.write_text(payload, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "AtlasRunConfig",
    "run_atlas_lab",
    "simulate_initial_angle_grid",
    "verify_atlas_lab_report",
]
