#!/usr/bin/env python3
"""Exact finite rigidity for the multiplicative monoid generated by 2 and 3.

Normalize E(2)=1 and write x=E(3). Ordering all 3-smooth integers through H
forces a rational interval containing log_2(3). The endpoints are computed by
exact integer comparisons of powers, not by floating-point logarithms.
"""

from __future__ import annotations

import argparse
import json
import math
from decimal import Decimal, localcontext
from fractions import Fraction


def max_power_exponent(base: int, height: int) -> int:
    if base < 2 or height < 1:
        raise ValueError("base must be at least 2 and height positive")
    exponent = 0
    power = 1
    while power * base <= height:
        power *= base
        exponent += 1
    return exponent


def exact_interval(height: int) -> dict[str, object]:
    """Return exact one-sided bounds for log_2(3) at size cutoff height."""
    if height < 3:
        raise ValueError("height must be at least 3")
    max_two = max_power_exponent(2, height)
    max_three = max_power_exponent(3, height)
    lower = Fraction(0, 1)
    upper: Fraction | None = None
    lower_witness = (0, 1)
    upper_witness: tuple[int, int] | None = None

    powers_two = [1]
    for _ in range(max_two):
        powers_two.append(powers_two[-1] * 2)
    powers_three = [1]
    for _ in range(max_three):
        powers_three.append(powers_three[-1] * 3)

    for denominator in range(1, max_three + 1):
        three_power = powers_three[denominator]
        for numerator in range(max_two + 1):
            candidate = Fraction(numerator, denominator)
            two_power = powers_two[numerator]
            if two_power < three_power and candidate > lower:
                lower = candidate
                lower_witness = (numerator, denominator)
            elif two_power > three_power and (upper is None or candidate < upper):
                upper = candidate
                upper_witness = (numerator, denominator)

    if upper is None or upper_witness is None:
        raise AssertionError("failed to produce an upper bound")
    if not 2 ** lower_witness[0] < 3 ** lower_witness[1]:
        raise AssertionError("invalid lower witness")
    if not 2 ** upper_witness[0] > 3 ** upper_witness[1]:
        raise AssertionError("invalid upper witness")

    width = upper - lower
    return {
        "height": height,
        "maximum_exponent_2": max_two,
        "maximum_exponent_3": max_three,
        "lower": lower,
        "upper": upper,
        "width": width,
        "lower_witness": lower_witness,
        "upper_witness": upper_witness,
    }


def decimal_log_ratio(digits: int) -> Decimal:
    with localcontext() as context:
        context.prec = digits + 10
        result = Decimal(3).ln() / Decimal(2).ln()
        context.prec = digits
        return +result


def continued_fraction(value: Decimal, terms: int) -> list[int]:
    digits: list[int] = []
    current = value
    for _ in range(terms):
        integer = int(current)
        digits.append(integer)
        remainder = current - integer
        if not remainder:
            break
        current = Decimal(1) / remainder
    return digits


def convergents(digits: list[int]) -> list[Fraction]:
    p_previous_previous, p_previous = 0, 1
    q_previous_previous, q_previous = 1, 0
    result: list[Fraction] = []
    for digit in digits:
        p = digit * p_previous + p_previous_previous
        q = digit * q_previous + q_previous_previous
        result.append(Fraction(p, q))
        p_previous_previous, p_previous = p_previous, p
        q_previous_previous, q_previous = q_previous, q
    return result


def intermediate_convergents(digits: list[int]) -> set[Fraction]:
    """Return convergents and semiconvergents represented by the digit prefix."""
    result: set[Fraction] = set()
    p_previous_previous, p_previous = 0, 1
    q_previous_previous, q_previous = 1, 0
    for index, digit in enumerate(digits):
        start = 1 if index else digit
        for multiplier in range(start, digit + 1):
            p = multiplier * p_previous + p_previous_previous
            q = multiplier * q_previous + q_previous_previous
            if q:
                result.add(Fraction(p, q))
        p = digit * p_previous + p_previous_previous
        q = digit * q_previous + q_previous_previous
        p_previous_previous, p_previous = p_previous, p
        q_previous_previous, q_previous = q_previous, q
    return result


def serialize_fraction(value: Fraction) -> str:
    return f"{value.numerator}/{value.denominator}"


def analyze(heights: list[int], digits: int = 100) -> dict[str, object]:
    alpha_decimal = decimal_log_ratio(digits)
    cf_digits = continued_fraction(alpha_decimal, 60)
    frontier = intermediate_convergents(cf_digits)
    rows: list[dict[str, object]] = []
    previous_log_height: float | None = None
    previous_width: float | None = None
    for height in heights:
        exact = exact_interval(height)
        lower = exact["lower"]
        upper = exact["upper"]
        width = exact["width"]
        assert isinstance(lower, Fraction)
        assert isinstance(upper, Fraction)
        assert isinstance(width, Fraction)
        log_height = math.log(height)
        width_float = float(width)
        local_exponent = None
        if previous_log_height is not None and previous_width is not None and width_float != previous_width:
            local_exponent = -math.log(width_float / previous_width) / math.log(
                log_height / previous_log_height
            )
        rows.append(
            {
                "height": height,
                "max_exponents": [exact["maximum_exponent_2"], exact["maximum_exponent_3"]],
                "lower": serialize_fraction(lower),
                "upper": serialize_fraction(upper),
                "exact_width": serialize_fraction(width),
                "width": width_float,
                "width_times_log_height_squared": width_float * log_height * log_height,
                "local_exponent_against_log_height": local_exponent,
                "lower_is_convergent_or_semiconvergent": lower in frontier,
                "upper_is_convergent_or_semiconvergent": upper in frontier,
                "lower_power_certificate": f"2^{lower.numerator} < 3^{lower.denominator}",
                "upper_power_certificate": f"3^{upper.denominator} < 2^{upper.numerator}",
            }
        )
        previous_log_height = log_height
        previous_width = width_float
    return {
        "theorem_tested": "All finite two-prime order constraints reduce to pure-power comparisons.",
        "normalization": "E(2)=1; target x=E(3)",
        "truth_decimal": str(alpha_decimal),
        "continued_fraction_prefix": cf_digits,
        "runs": rows,
    }


def parse_height(text: str) -> int:
    if text.startswith("10^"):
        return 10 ** int(text[3:])
    return int(text)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--heights",
        nargs="+",
        type=parse_height,
        default=[10**2, 10**3, 10**4, 10**6, 10**10, 10**20, 10**50, 10**100],
    )
    parser.add_argument("--digits", type=int, default=100)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print(json.dumps(analyze(args.heights, args.digits), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()

